name: Clang Format

on: [ push, pull_request ]

jobs:
  format:
    name: Format Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install latest clang-format
        run: |
          sudo apt-get update
          sudo apt-get install clang-format

      - name: Format Code
        run: |
          cp .github/.clang-format .
          find . -name '*.h' -or -name '*.cpp' -or -name '*.cc' | xargs clang-format -style=file -i

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git diff --exit-code || (git commit -am "Apply clang-format" && git push)
