name: Clang Format

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  cpp-formatting-check:
    name: Cpp Formatting Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        check:
          - 'src/include/optimizer/*.{cpp,h}'
    steps:
      - uses: actions/checkout@v3
      - name: Run clang-format style check for C/C++ programs.
        uses: jidicula/clang-format-action@v4.11.0
        with:
          clang-format-version: '13'
          check-path: ${{ matrix.check }}

